//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int idPurchase { get; set; }
        public string Bank { get; set; }
        public int idUser { get; set; }
        public int idGame { get; set; }
        public int cardNumber { get; set; }
        public string term { get; set; }
        public int cvv { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Users Users { get; set; }
    }
}
